### ISSUE TITLE
Is it possible to update single GUI elements in a handler call before it returns?

### ISSUE THREAD

**Issue by jranke** [jverzani/gWidgetsWWW2#26]
I would like to update the status bar or a GLabel within a handler function - is there a way to do this?
```{r}
w <- gwindow()
gg <- ggroup(cont = w, horizontal = FALSE)
changing_label <- glabel("Not running", cont = gg)
gbutton("Run", handler = function(h, ...) {
            svalue(changing_label) <- "Running"
            cat("\nRunning")
            Sys.sleep(3)  
            cat("\nNot running")
            svalue(changing_label) <- "Not running"
}, cont = gg)
```
I also tried to implement a GProgressBar which would be even nicer...

**Comment by jranke** [comment]
The solution I found involves the gconfirm dialog, as it does not block the R process:

```{r}
w <- gwindow()
gg <- ggroup(cont = w, horizontal = FALSE)
changing_label <- glabel("Not running", cont = gg)
pre_run_msg <- paste("After pressing 'Yes', the progress of XY can be followed ",
                     "in the R console. To cancel, change to the R console and ", 
                     "press Esc (on Windows) or Ctrl-C (on Linux/Unix)")
gbutton("Run", handler = function(h, ...) {
  gconfirm(pre_run_msg, handler = function(h, ...) {
    for (i in 1:10) {
      Sys.sleep(0.2)  
      print(i)
    }
    svalue(changing_label) <- "Terminated"
    })
  svalue(changing_label) <- "Running"
}, cont = gg)
```

**Comment by jverzani** [comment]
Doesn't `svalue(sb) <- "new value"` work (where `sb` is a `gstatusbar` object)?

However, we should have a `gprogressbar` constructor. There is one in regular `gWidgets2`.

**Comment by jranke** [comment]
In the above example, a statusbar can be used instead of a glabel, yes. But if I try to set it within the loop, it is only updated when the handler function returns.

Yes, a gprogressbar that could be updated from a long-lasting progress would be great.

**Comment by jverzani** [comment]
Yeah, I see the issue. Thanks. I thought adding a call to `w$toplevel$js_queue$flush()` in the handler might work, but it doesn't. Seems like the workaround you found should be made more general and more accessible.

**Comment by jranke** [comment]
Yes, it's just that I seem to be the only person actually using this toolkit at the moment... And unless we find a way to get the performance issue sorted, clean everything nicely and upload to CRAN, it will probably stay that way - which is fine with me, but somehow a pity, given all the work and ingenious development that you have put in!
